In [11]:
import numpy as np
import pandas as pd
from sklearn import datasets, svm,metrics
import matplotlib.pyplot as plt

Base de Dados do Sklearn

In [22]:
digitos=datasets.load_digits()

In [13]:
print(digitos.DESCR)

.. _digits_dataset:

Optical recognition of handwritten digits dataset
--------------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 1797
    :Number of Attributes: 64
    :Attribute Information: 8x8 image of integer pixels in the range 0..16.
    :Missing Attribute Values: None
    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)
    :Date: July; 1998

This is a copy of the test set of the UCI ML hand-written digits datasets
https://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits

The data set contains images of hand-written digits: 10 classes where
each class refers to a digit.

Preprocessing programs made available by NIST were used to extract
normalized bitmaps of handwritten digits from a preprinted form. From a
total of 43 people, 30 contributed to the training set and different 13
to the test set. 32x32 bitmaps are divided into nonoverlapping blocks of
4x4 and the number of on pixels are counted in each blo

In [24]:
digitos.images

array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ..., 15.,  5.,  0.],
        [ 0.,  3., 15., ..., 11.,  8.,  0.],
        ...,
        [ 0.,  4., 11., ..., 12.,  7.,  0.],
        [ 0.,  2., 14., ..., 12.,  0.,  0.],
        [ 0.,  0.,  6., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
        [ 0.,  0.,  0., ...,  9.,  0.,  0.],
        [ 0.,  0.,  3., ...,  6.,  0.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.]],

       [[ 0.,  0.,  0., ..., 12.,  0.,  0.],
        [ 0.,  0.,  3., ..., 14.,  0.,  0.],
        [ 0.,  0.,  8., ..., 16.,  0.,  0.],
        ...,
        [ 0.,  9., 16., ...,  0.,  0.,  0.],
        [ 0.,  3., 13., ..., 11.,  5.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.]],

       ...,

       [[ 0.,  0.,  1., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ...,  2.,  1.,  0.],
        [ 0.,  0., 16., ..., 16.,  5.,  0.

In [23]:
#Visualizando a variável Target
digitos.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
N_samples=len(digitos.images)
dados=digitos.images.reshape((N_samples,-1))
classe=digitos.target

In [31]:
dados=pd.DataFrame(dados)
dados['classe']=classe

In [32]:
dados.head()

0    1    2     3     4     5    6    7    8    9  ...   55   56   57  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  0.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

    58    59    60    61   62   63  classe  
0  6.0  13.0  10.0   0.0  0.0  0.0       0  
1  0.0  11.0  16.0  10.0  0.0  0.0       1  
2  0.0   3.0  11.0  16.0  9.0  0.0       2  
3  7.0  13.0  13.0   9.0  0.0  0.0       3  
4  0.0   2.0  16.0   4.0  0.0  0.0       4  

[5 rows x 65 columns]

In [49]:
from sklearn.model_selection import train_test_split
x=dados.iloc[:,0:64].values
y=dados.iloc[:,64]
Xtreino,Xteste,Ytreino,Yteste= train_test_split(x,y,test_size=0.3)

In [50]:
Xtreino.shape

(1257, 64)

In [51]:
Xteste.shape

(540, 64)

Normalizando os dados

In [52]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(Xtreino)
Xtreino=scaler.transform(Xtreino)
Xteste=scaler.transform(Xteste)


Treinando o Modelo

In [53]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(Xtreino,Ytreino)

KNeighborsClassifier(n_neighbors=3)

In [54]:
Yprev=knn.predict(Xteste)

In [58]:
from sklearn import metrics
print(metrics.classification_report(Yteste,Yprev))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        55
           1       0.93      1.00      0.97        57
           2       0.96      0.98      0.97        54
           3       1.00      0.92      0.96        51
           4       1.00      0.90      0.95        51
           5       0.94      0.98      0.96        61
           6       1.00      1.00      1.00        42
           7       0.93      0.98      0.96        56
           8       0.95      0.95      0.95        55
           9       0.95      0.91      0.93        58

    accuracy                           0.96       540
   macro avg       0.97      0.96      0.96       540
weighted avg       0.96      0.96      0.96       540



In [59]:
from sklearn.metrics import  confusion_matrix
matriz_conf=confusion_matrix(Yteste,Yprev)
print(matriz_conf)

[[55  0  0  0  0  0  0  0  0  0]
 [ 0 57  0  0  0  0  0  0  0  0]
 [ 0  1 53  0  0  0  0  0  0  0]
 [ 0  0  0 47  0  0  0  2  0  2]
 [ 0  0  0  0 46  0  0  2  3  0]
 [ 0  0  0  0  0 60  0  0  0  1]
 [ 0  0  0  0  0  0 42  0  0  0]
 [ 0  0  1  0  0  0  0 55  0  0]
 [ 0  2  1  0  0  0  0  0 52  0]
 [ 0  1  0  0  0  4  0  0  0 53]]


Utilizando Validação Cruzada

In [61]:
from sklearn.model_selection import cross_val_score
scores=cross_val_score(knn,x,y,cv=5)
scores

array([0.95555556, 0.95833333, 0.96657382, 0.98607242, 0.96657382])